### PR TITLE
engine/tester: fix build on systems without color

### PR DESCRIPTION
**Pull request by okt-galaktionov**
Provide the necessary definitions and fix other compilation errors.

Testing done: fixed build issues on Linux distros where meson fails to find the curses library

### CODE REVIEW

**Review by ol-arteman — CHANGES_REQUESTED** [review]
The patch is somewhat strange:
- what does "color" mean here exactly?
- I assume it is somehow related to `curses`. Are there any reasonable systems w/o `curses`?

**Comment by ol-arteman** [comment]
Sorry, I am not buying this so far. Would you mind providing an example of a system where this problem could arise?

**Comment by ol-arteman** [comment]
Still I think the right fix is to detect libncurses properly and also I don't think we need to bump the minimum required version Meson for that. I suppose that our build should instead try to link with `libncurses` instead of `libcurses`,

**Review by ol-andrewr — APPROVED** [review]
IMHO it is a step in a right direction and we should accept it.
The patch fixes existing problem.
Yes, better more general solutions exist, but until we have them, we should accept this fix which is valid.

**Comment by ol-arteman** [comment]
Ok, I totally agree that the patch is useful, but the commit message is _utterly_ misleading, because the problem has nothing to do with any kind of color. I suggest that the summary line be like _fix build when curses is missing_ and the description outline cases where it could be possible (basically what you've already told here in PR comments). You may also provide a link to a Gentoo bug in a `Link` trailer.

**Review by ol-arteman — APPROVED** [review]

**Pull request closed without merging**
